### ISSUE TITLE
Load only relevant images into Aladin Lite dropdown

### ISSUE THREAD

**Issue by vorugantia** [gammapy/gamma-sky#48]
Most of the default images loaded by Aladin Lite in the dropdown tool are not relevant to us, and instead we want to add other high-energy images to the dropdown, like those from the Planck satellite.

There is no information on configuring the dropdown in the Aladin Lite docs. In order to figure it out ourselves, here are important lines in `aladin.js`:
- [HpxImageSurvey.SURVEYS[]](https://github.com/gammapy/gamma-sky/blob/gh-pages/static/aladin.js#L8065)
- [HpxImageSurvey.getAvailableSurveys()](https://github.com/gammapy/gamma-sky/blob/gh-pages/static/aladin.js#L8190)
- [Aladin.prototype.updateSurveysDropdownList()](https://github.com/gammapy/gamma-sky/blob/gh-pages/static/aladin.js#L10931)
- [survey <select>](https://github.com/gammapy/gamma-sky/blob/gh-pages/static/aladin.js#L11429)

I've tried calling `declare var HpxImageSurvey: any` etc. and then using the functions in our own code, but it was not working for me.

**Comment by cdeil** [comment]
I had a quick look.

My understanding is that `aladin.updateSurveysDropdownList` is exactly what we want.

There's one example where it's called with the default array of objects `SURVEYS`, returned via `getAvailableSurveys`.

@vorugantia - Can you please try again and share the example where you tried calling `aladin.updateSurveysDropdownList`?

Maybe you could make a http://plnkr.co/ for that and share the link to it here, so that we can both easily try to get the same example to work?

If Plunker doesn't work for some reason, there's other such JS share pages. E.g. here's an example that Thomas shared with me at some point via email how to do something in Aladin Lite:
http://jsbin.com/pededeqe/1/edit?html,output

**Comment by vorugantia** [comment]
@cdeil Here it is:

http://jsbin.com/kepogav/11/edit?js,console,output

**Comment by cdeil** [comment]
This is what I think should work:
http://plnkr.co/edit/SshX90zQTWmJuujXXedz?p=preview
It doesn't.

**Comment by vorugantia** [comment]
Issue has been resolved in #50.
