### ISSUE TITLE
AL map freezes during catalog load

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-sky#7]
I noticed that the Aladin Lite (AL) map freezes for a second while the Fermi catalog is loading.
@vorugantia - Can you try and play around with this and see if this can be avoided?

The goal is that the map is responsive ASAP and that other info, like this catalog, gets displayed whenever it arrives.

(I didn't look myself how the catalog loading works ... is `A.catalogFromVizieR` or `aladin.addCatalog` blocking? Is there a way to have it non-blocking?)

**Comment by vorugantia** [comment]
@cdeil - `A.catalogFromVizieR` is causing the freeze. It's taking so long because we set the catalog to load on the entire map. The field of view attribute is set to 180 right now but if you set it to a low number like 5, AL loads much faster. 

I'm not sure how we can prevent the lag while still displaying all labels... we'll have to figure something out. I can look into it this weekend.

**Comment by vorugantia** [comment]
No longer using `A.catalogFromVizieR` and instead loading local catalogs, so the issue has been resolved.
