### ISSUE TITLE
Search prompt does work with 'common name'

### ISSUE THREAD

**Issue by joleroi** [gammapy/gamma-sky#90]
The search prompt in the catalog view of gamma-sky.net only works with the ``common name`` of a source.

For example if I want the VHE Energy source at the GC, I have to type 'Galactic Center', 'HESS J1745-290' does not work. This is confusing, because for other sources (e.g. HESS J1745-303) the "HESS name" is the common name so when I start typing 'HESS J...' I do get suggestions, they just don't contain the source I'm looking for (HESS J1745-290).

I would suggest to also prompt ``Gamma names``, ``Fermi names``, and ``other names`` in the search prompt, unless there is a technical reason not to do so.

**Comment by cdeil** [comment]
@joleroi - Agreed that this should be implemented.

The info is available in gamma-cat already in the "gamma_names" key:
```
  - source_id: 106
  - common_name: Galactic Centre
  - gamma_names: HESS J1745-290,VER J1745-290
  - fermi_names: ''
  - other_names: Sgr A*,Sagittarius A*
```

https://github.com/gammapy/gamma-cat/blob/6c9a129f3d96d37e19888bc3efae69154d37dcf3/docs/data/gammacat.yaml#L9076

@vorugantia - How much work would it be to add the strings from "gamma_names" to the search field?
I never looked at your implementation and don't have time to add it. So unless you have time, please put a very short description what needs to be done here, so that someone can implement this in the future if they want to.

**Comment by vorugantia** [comment]
#92 includes the implementation of more search entries for the TeV sources. We could do the same for 3FGL and 3FHL as well. @cdeil - have a look at the code, and then we'll merge the PR after review.

**Comment by cdeil** [comment]
@joleroi - Please try again, I think this issue is resolved.

![screen shot 2017-09-15 at 10 48 57](https://user-images.githubusercontent.com/852409/30474311-8dd90918-9a03-11e7-9a7b-1345f3f35c2b.png)
