### ISSUE TITLE
3FHL sources show up with 2 different spectra

### ISSUE THREAD

**Issue by joleroi** [gammapy/gamma-sky#91]
For 3FHL sources, the webpage shows two different sets of spectral parameters

See e.g. http://gamma-sky.net/#/cat/3fhl/0

```
Model Info

    Significance (10 GeV - 2 TeV): 5.362
    Npred: 7.63

    Spectrum type: PowerLaw
        Spectral index: 1.672 +/- 0.827
        Pivot energy: 23.7 GeV
        Flux density at pivot energy: 5.32e-13 +/- 2.10e-13 cm-2 s-1 GeV-1

    Power law index: 2.223 +/- 0.481
    Integral flux (10 GeV - 1 TeV): 2.96e-11 +/- 1.17e-11 cm-2 s-1
    Energy flux (10 GeV - 1 TeV): 1.68e-12 +/- 1.07e-12 erg cm-2 s-1
    Significance curvature: 1.02
```

If there is a good reason for that it should be explained somewhere, because the way it is right now might confuse people.

**Comment by cdeil** [comment]
Yes, this can be improved a bit. Assigning to myself. It's a bit related to https://github.com/gammapy/gammapy/pull/1127 which I had planned to finish up tomorrow anyways.

**Comment by cdeil** [comment]
@joleroi - Turns out that in 3FHL every source has a PL and CPL measured.
I've tried to make the display clearer in 22074c27 , it now looks like this:
---
<img width="563" alt="screen shot 2017-09-15 at 14 42 36" src="https://user-images.githubusercontent.com/852409/30482666-494a757c-9a24-11e7-9362-b19cadee1ca9.png">
---
This change is not deployed yet to the public webpage, it'll come with other improvements on the next deploy.

If you want, you can compare with the printout we have in Gammapy for a PL and CPL source:
```
python -c 'from gammapy.catalog import source_catalogs; print(source_catalogs["3fhl"][352])'
python -c 'from gammapy.catalog import source_catalogs; print(source_catalogs["3fhl"][1442])'
```
I'm very short on time, so generally pull requests in Gammapy or here are preferred, but of course reminder issues are also welcome.

@joleroi - Any further suggestions to improve or close the issue?
